# @USER_TOKEN my_token_value
# @name readlog


### HEALTH CHECK

GET http://localhost:8080/api/health HTTP/1.1
Accept: application/json
Content-Type: application/json


### CREATE A NEW USER

POST http://localhost:8080/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "accountType": 0,
  "email": "delafiado@gmail.com",
  "password": "delafiador@123password",
  "username": "del_fiador"
}


### LOGIN A USER

POST http://localhost:8080/api/auth/login HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "email": "delafiado@gmail.com",
  "password": "delafiador@123password"
}
